services:

  db:
    image: postgres:16-alpine
    container_name: fij_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: evangile
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Meli123christ
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d evangile"]
      interval: 5s
      timeout: 5s
      retries: 10
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 256M

  app:
    build: .
    container_name: fij_app
    restart: unless-stopped
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: 512M

volumes:
  postgres_data:
